name: inductiva

channels:
  - conda-forge
  - defaults

dependencies:
  - python==3.11
  - yapf
  - pylint
  - pytest
  - pip
  - pip:
    - -r requirements.txt
    - -r docs/requirements.txt
    - -e .
