import os
import MDAnalysis as mda
import nglview as nv
from pathlib import Path
from inductiva.molecules.scenarios._post_processing import MovieMaker

class MDWaterBoxSimulationOutput:
    """Post process a GROMACS simulation outputs."""

    def __init__(self, sim_output_path: Path = None):
        """Initializes a `SimulationOutput` object.

        Given a simulation output directory that contains the standard files
        generated by a GROMACS simulation run, this class provides methods to
        visualize the simulation outputs in a notebook.

        Args:
            sim_output_path: Path to the simulation output directory."""

        self.sim_output_dir = sim_output_path

    def visualize(self):
        """Visualize the simulation outputs in a notebook using NGLView."""

        topology = os.path.join(self.sim_output_dir, "eql.tpr")
        trajectory = os.path.join(self.sim_output_dir, "eql.xtc")
        universe = mda.Universe(topology, trajectory, all_coordinates=True)
        atoms = universe.atoms

        transformation = mda.transformations.unwrap(atoms)
        universe.trajectory.add_transformations(transformation)

        view = nv.show_mdanalysis(universe)
        view.add_ball_and_stick("all")
        view.center()
        view.parameters = {
            "backgroundColor": "white"
        }  # Set the background color
        return view
    
    def render_movie(self, view,save_path: Path = None, fps=8, start=0,stop=-1): 
        movie = MovieMaker(view, output=save_path, fps=fps, start=start, stop=stop)
        movie.make()
