# coding: utf-8

"""
    InductivaWebAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from inductiva.client.models.cost_components import CostComponents
from inductiva.client.models.cost_components_partial import CostComponentsPartial
from inductiva.client.models.cost_type import CostType
from typing import Optional, Set
from typing_extensions import Self


class CostDetail(BaseModel):
    """
    CostDetail
    """

  # noqa: E501
    month: StrictStr
    total: Union[StrictFloat, StrictInt]
    components: CostComponents
    undiscounted_components: Optional[CostComponentsPartial] = None
    type: CostType
    warning: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = [
        "month", "total", "components", "undiscounted_components", "type",
        "warning"
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CostDetail from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of components
        if self.components:
            _dict['components'] = self.components.to_dict()
        # override the default output from pydantic by calling `to_dict()` of undiscounted_components
        if self.undiscounted_components:
            _dict[
                'undiscounted_components'] = self.undiscounted_components.to_dict(
                )
        # set to None if undiscounted_components (nullable) is None
        # and model_fields_set contains the field
        if self.undiscounted_components is None and "undiscounted_components" in self.model_fields_set:
            _dict['undiscounted_components'] = None

        # set to None if warning (nullable) is None
        # and model_fields_set contains the field
        if self.warning is None and "warning" in self.model_fields_set:
            _dict['warning'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CostDetail from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "month":
                obj.get("month"),
            "total":
                obj.get("total"),
            "components":
                CostComponents.from_dict(obj["components"])
                if obj.get("components") is not None else None,
            "undiscounted_components":
                CostComponentsPartial.from_dict(obj["undiscounted_components"])
                if obj.get("undiscounted_components") is not None else None,
            "type":
                obj.get("type"),
            "warning":
                obj.get("warning")
        })
        return _obj
