# coding: utf-8

"""
    InductivaWebAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class ProcessorType(str, Enum):
    """
    Types of processors that simulators can use.     
    """
    """
    allowed enum values
    """
    CPU = 'cpu'
    GPU = 'gpu'
    CPU_GPU = 'cpu_gpu'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of ProcessorType from a JSON string"""
        return cls(json.loads(json_str))
