# coding: utf-8

"""
    InductivaWebAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictInt
from typing import Any, ClassVar, Dict, List
from inductiva.client.models.machine_type_with_spot_price import MachineTypeWithSpotPrice
from typing import Optional, Set
from typing_extensions import Self


class SimulatorWithMachineTypesPaginated(BaseModel):
    """
    Schema for paginated available machine types (simple).
    """ # noqa: E501
    available_machine_types: List[MachineTypeWithSpotPrice]
    total_size: StrictInt
    __properties: ClassVar[List[str]] = [
        "available_machine_types", "total_size"
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SimulatorWithMachineTypesPaginated from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in available_machine_types (list)
        _items = []
        if self.available_machine_types:
            for _item_available_machine_types in self.available_machine_types:
                if _item_available_machine_types:
                    _items.append(_item_available_machine_types.to_dict())
            _dict['available_machine_types'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SimulatorWithMachineTypesPaginated from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "available_machine_types": [
                MachineTypeWithSpotPrice.from_dict(_item)
                for _item in obj["available_machine_types"]
            ] if obj.get("available_machine_types") is not None else None,
            "total_size":
                obj.get("total_size")
        })
        return _obj
