# coding: utf-8

"""
    InductivaWebAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from inductiva.client.models.trigger_observer_type import TriggerObserverType
from typing import Optional, Set
from typing_extensions import Self


class TriggerObserverCreate(BaseModel):
    """
    TriggerObserverCreate
    """

  # noqa: E501
    trigger_type: StrictStr
    task_id: StrictStr
    trigger: TriggerObserverType
    file_path: Optional[StrictStr] = None
    regex: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = [
        "trigger_type", "task_id", "trigger", "file_path", "regex"
    ]

    @field_validator('trigger_type')
    def trigger_type_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['observer']):
            raise ValueError("must be one of enum values ('observer')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of TriggerObserverCreate from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if file_path (nullable) is None
        # and model_fields_set contains the field
        if self.file_path is None and "file_path" in self.model_fields_set:
            _dict['file_path'] = None

        # set to None if regex (nullable) is None
        # and model_fields_set contains the field
        if self.regex is None and "regex" in self.model_fields_set:
            _dict['regex'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of TriggerObserverCreate from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "trigger_type": obj.get("trigger_type"),
            "task_id": obj.get("task_id"),
            "trigger": obj.get("trigger"),
            "file_path": obj.get("file_path"),
            "regex": obj.get("regex")
        })
        return _obj
