# coding: utf-8
"""
    InductivaWebAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from inductiva.client import schemas  # noqa: F401


class ActionWebhookInfo(schemas.DictSchema):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    class MetaOapg:
        required = {
            "webhook_url",
            "action_type",
        }

        class properties:

            class action_type(schemas.EnumBase, schemas.StrSchema):

                @schemas.classproperty
                def WEBHOOK(cls):
                    return cls("webhook")

            class webhook_url(schemas.StrSchema):
                pass

            __annotations__ = {
                "action_type": action_type,
                "webhook_url": webhook_url,
            }

    webhook_url: MetaOapg.properties.webhook_url
    action_type: MetaOapg.properties.action_type

    @typing.overload
    def __getitem__(
        self, name: typing_extensions.Literal["action_type"]
    ) -> MetaOapg.properties.action_type:
        ...

    @typing.overload
    def __getitem__(
        self, name: typing_extensions.Literal["webhook_url"]
    ) -> MetaOapg.properties.webhook_url:
        ...

    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema:
        ...

    def __getitem__(self, name: typing.Union[typing_extensions.Literal[
        "action_type",
        "webhook_url",
    ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)

    @typing.overload
    def get_item_oapg(
        self, name: typing_extensions.Literal["action_type"]
    ) -> MetaOapg.properties.action_type:
        ...

    @typing.overload
    def get_item_oapg(
        self, name: typing_extensions.Literal["webhook_url"]
    ) -> MetaOapg.properties.webhook_url:
        ...

    @typing.overload
    def get_item_oapg(
            self, name: str
    ) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]:
        ...

    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal[
        "action_type",
        "webhook_url",
    ], str]):
        return super().get_item_oapg(name)

    def __new__(
        cls,
        *_args: typing.Union[
            dict,
            frozendict.frozendict,
        ],
        webhook_url: typing.Union[
            MetaOapg.properties.webhook_url,
            str,
        ],
        action_type: typing.Union[
            MetaOapg.properties.action_type,
            str,
        ],
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict,
                               frozendict.frozendict, str, date, datetime,
                               uuid.UUID, int, float, decimal.Decimal, None,
                               list, tuple, bytes],
    ) -> 'ActionWebhookInfo':
        return super().__new__(
            cls,
            *_args,
            webhook_url=webhook_url,
            action_type=action_type,
            _configuration=_configuration,
            **kwargs,
        )
