# coding: utf-8
"""
    InductivaWebAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from inductiva.client import schemas  # noqa: F401


class OperationStart(schemas.DictSchema):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    class MetaOapg:
        required = {
            "elapsed_time_s",
            "name",
            "attributes",
        }

        class properties:
            elapsed_time_s = schemas.NumberSchema

            @staticmethod
            def name() -> typing.Type['TaskOperationName']:
                return TaskOperationName

            attributes = schemas.DictSchema
            __annotations__ = {
                "elapsed_time_s": elapsed_time_s,
                "name": name,
                "attributes": attributes,
            }

    elapsed_time_s: MetaOapg.properties.elapsed_time_s
    name: 'TaskOperationName'
    attributes: MetaOapg.properties.attributes

    @typing.overload
    def __getitem__(
        self, name: typing_extensions.Literal["elapsed_time_s"]
    ) -> MetaOapg.properties.elapsed_time_s:
        ...

    @typing.overload
    def __getitem__(
            self,
            name: typing_extensions.Literal["name"]) -> 'TaskOperationName':
        ...

    @typing.overload
    def __getitem__(
        self, name: typing_extensions.Literal["attributes"]
    ) -> MetaOapg.properties.attributes:
        ...

    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema:
        ...

    def __getitem__(self, name: typing.Union[typing_extensions.Literal[
        "elapsed_time_s",
        "name",
        "attributes",
    ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)

    @typing.overload
    def get_item_oapg(
        self, name: typing_extensions.Literal["elapsed_time_s"]
    ) -> MetaOapg.properties.elapsed_time_s:
        ...

    @typing.overload
    def get_item_oapg(
            self,
            name: typing_extensions.Literal["name"]) -> 'TaskOperationName':
        ...

    @typing.overload
    def get_item_oapg(
        self, name: typing_extensions.Literal["attributes"]
    ) -> MetaOapg.properties.attributes:
        ...

    @typing.overload
    def get_item_oapg(
            self, name: str
    ) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]:
        ...

    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal[
        "elapsed_time_s",
        "name",
        "attributes",
    ], str]):
        return super().get_item_oapg(name)

    def __new__(
        cls,
        *_args: typing.Union[
            dict,
            frozendict.frozendict,
        ],
        elapsed_time_s: typing.Union[
            MetaOapg.properties.elapsed_time_s,
            decimal.Decimal,
            int,
            float,
        ],
        name: 'TaskOperationName',
        attributes: typing.Union[
            MetaOapg.properties.attributes,
            dict,
            frozendict.frozendict,
        ],
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict,
                               frozendict.frozendict, str, date, datetime,
                               uuid.UUID, int, float, decimal.Decimal, None,
                               list, tuple, bytes],
    ) -> 'OperationStart':
        return super().__new__(
            cls,
            *_args,
            elapsed_time_s=elapsed_time_s,
            name=name,
            attributes=attributes,
            _configuration=_configuration,
            **kwargs,
        )


from inductiva.client.model.task_operation_name import TaskOperationName
