# coding: utf-8
"""
    InductivaWebAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from inductiva.client import schemas  # noqa: F401


class TopUpType(schemas.EnumBase, schemas.StrSchema):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    An enumeration.
    """

    @schemas.classproperty
    def INITIAL_CREDITS(cls):
        return cls("initial_credits")

    @schemas.classproperty
    def OFFER(cls):
        return cls("offer")

    @schemas.classproperty
    def STRIPE_PAYMENT(cls):
        return cls("stripe_payment")

    @schemas.classproperty
    def BOOST(cls):
        return cls("boost")
