# coding: utf-8
"""
    InductivaWebAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from inductiva.client import schemas  # noqa: F401


class UserCreate(schemas.DictSchema):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    Class to be used in place of Pydantic's BaseModel.

Currently, FastAPI and Pydantic don't generate an OpenAPI specification
that correctly handles optional fields, i.e., fields that can be None.
This results in the client generator not being able to generate a client
that works correctly.
Since some of our return types have optional attributes, e.g. TaskStatus,
this class adds a generic workaround. The workaround was taken from
https://github.com/pydantic/pydantic/issues/1270.
There you can also find more information about this issue, which (as per
information on the issue), will only be adressed in Pydantic's version 2.
    """

    class MetaOapg:
        required = {
            "api_key",
            "username",
        }

        class properties:
            username = schemas.StrSchema
            api_key = schemas.StrSchema
            __annotations__ = {
                "username": username,
                "api_key": api_key,
            }

    api_key: MetaOapg.properties.api_key
    username: MetaOapg.properties.username

    @typing.overload
    def __getitem__(
        self, name: typing_extensions.Literal["username"]
    ) -> MetaOapg.properties.username:
        ...

    @typing.overload
    def __getitem__(
        self, name: typing_extensions.Literal["api_key"]
    ) -> MetaOapg.properties.api_key:
        ...

    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema:
        ...

    def __getitem__(self, name: typing.Union[typing_extensions.Literal[
        "username",
        "api_key",
    ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)

    @typing.overload
    def get_item_oapg(
        self, name: typing_extensions.Literal["username"]
    ) -> MetaOapg.properties.username:
        ...

    @typing.overload
    def get_item_oapg(
        self, name: typing_extensions.Literal["api_key"]
    ) -> MetaOapg.properties.api_key:
        ...

    @typing.overload
    def get_item_oapg(
            self, name: str
    ) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]:
        ...

    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal[
        "username",
        "api_key",
    ], str]):
        return super().get_item_oapg(name)

    def __new__(
        cls,
        *_args: typing.Union[
            dict,
            frozendict.frozendict,
        ],
        api_key: typing.Union[
            MetaOapg.properties.api_key,
            str,
        ],
        username: typing.Union[
            MetaOapg.properties.username,
            str,
        ],
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict,
                               frozendict.frozendict, str, date, datetime,
                               uuid.UUID, int, float, decimal.Decimal, None,
                               list, tuple, bytes],
    ) -> 'UserCreate':
        return super().__new__(
            cls,
            *_args,
            api_key=api_key,
            username=username,
            _configuration=_configuration,
            **kwargs,
        )
