# coding: utf-8
"""
    InductivaWebAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from inductiva.client import schemas  # noqa: F401


class UserEmailOrganization(schemas.DictSchema):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    class MetaOapg:
        required = {
            "organization",
            "organization_id",
            "email",
        }

        class properties:
            email = schemas.StrSchema
            organization = schemas.StrSchema
            organization_id = schemas.StrSchema
            __annotations__ = {
                "email": email,
                "organization": organization,
                "organization_id": organization_id,
            }

    organization: MetaOapg.properties.organization
    organization_id: MetaOapg.properties.organization_id
    email: MetaOapg.properties.email

    @typing.overload
    def __getitem__(
            self, name: typing_extensions.Literal["email"]
    ) -> MetaOapg.properties.email:
        ...

    @typing.overload
    def __getitem__(
        self, name: typing_extensions.Literal["organization"]
    ) -> MetaOapg.properties.organization:
        ...

    @typing.overload
    def __getitem__(
        self, name: typing_extensions.Literal["organization_id"]
    ) -> MetaOapg.properties.organization_id:
        ...

    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema:
        ...

    def __getitem__(self, name: typing.Union[typing_extensions.Literal[
        "email",
        "organization",
        "organization_id",
    ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)

    @typing.overload
    def get_item_oapg(
            self, name: typing_extensions.Literal["email"]
    ) -> MetaOapg.properties.email:
        ...

    @typing.overload
    def get_item_oapg(
        self, name: typing_extensions.Literal["organization"]
    ) -> MetaOapg.properties.organization:
        ...

    @typing.overload
    def get_item_oapg(
        self, name: typing_extensions.Literal["organization_id"]
    ) -> MetaOapg.properties.organization_id:
        ...

    @typing.overload
    def get_item_oapg(
            self, name: str
    ) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]:
        ...

    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal[
        "email",
        "organization",
        "organization_id",
    ], str]):
        return super().get_item_oapg(name)

    def __new__(
        cls,
        *_args: typing.Union[
            dict,
            frozendict.frozendict,
        ],
        organization: typing.Union[
            MetaOapg.properties.organization,
            str,
        ],
        organization_id: typing.Union[
            MetaOapg.properties.organization_id,
            str,
        ],
        email: typing.Union[
            MetaOapg.properties.email,
            str,
        ],
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict,
                               frozendict.frozendict, str, date, datetime,
                               uuid.UUID, int, float, decimal.Decimal, None,
                               list, tuple, bytes],
    ) -> 'UserEmailOrganization':
        return super().__new__(
            cls,
            *_args,
            organization=organization,
            organization_id=organization_id,
            email=email,
            _configuration=_configuration,
            **kwargs,
        )
