name: GH Pages Deploy

on:
  push:
    branches: [main, development]
    paths-ignore:
      - README.md

jobs:
  build-deploy:
    name: Build and deploy

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
          path: source

      - uses: actions/checkout@v3
        with:
          ref: development
          path: source-dev

      - name: Install dependencies
        run: |
          cd source
          python -m pip install -r requirements.txt
          cd docs
          python -m pip install -r requirements.txt

      - uses: actions/checkout@v3
        with:
          ref: gh-pages
          path: build

      - name: remove all files on the build folder
        working-directory: build
        run: rm -vfr *

      - name: Build "main" docs with Sphinx
        run: |
          cd source/docs
          sphinx-build . ../../build/en/latest -D version=latest      

      - name: Build "dev" docs with Sphinx
        run: |
          cd source-dev/docs
          sphinx-build . ../../build/en/development -W -D version=development      

      - name: disable jekyll
        working-directory: build
        run: touch .nojekyll

      - name: create subdomain CNAME file
        working-directory: build
        run: echo docs.inductiva.ai > CNAME

      - name: configure client side redirection
        working-directory: source/docs
        run: cp redirect.html ../../build/index.html

      - name: copy robots.txt file to root
        working-directory: source/docs
        run: cp robots.txt ../../build/

      - name: Commit and push changes to gh-pages
        working-directory: build
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git add .
          git commit -m "Update GitHub pages from Sphinx build for commit ${GITHUB_SHA}"
          git push origin gh-pages
