name: GH Pages Deploy

on:
  push:
    branches: [main, development]
    paths-ignore:
      - README.md

jobs:
  build-deploy:
    name: Build and deploy

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: main
          path: source

      - uses: actions/checkout@v2
        with:
          ref: development
          path: source-dev

      - uses: actions/checkout@v2
        with:
          ref: gh-pages
          path: build

      - uses: nicholasphair/sphinx-action@7.0.0
        with:
          docs-folder: "source/docs/"
          # required by #1291
          pre-build-command: "apt-get update -y && apt-get install -y git"
          build-command: "sphinx-build . ../../build/en/latest"

      - uses: nicholasphair/sphinx-action@7.0.0
        with:
          docs-folder: "source-dev/docs/"
          # required by #1291
          pre-build-command: "apt-get update -y && apt-get install -y git"
          build-command: "sphinx-build . ../../build/en/development"

      - name: disable jekyll
        working-directory: build
        run: touch .nojekyll

      - name: redirect to latest
        working-directory: build
        run: echo "<meta http-equiv=\"Refresh\" content=\"0; url='/en/latest/'\" />" > "index.html"

      - name: Commit and push changes to gh-pages
        working-directory: build
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git add .
          git commit -m "Update GitHub pages from Sphinx build for commit ${GITHUB_SHA}"
          git push origin gh-pages
