name: GH Pages Deploy

on:
  push:
    branches: [main, development]
    paths-ignore:
      - README.md

jobs:
  build-deploy:
    name: Build and deploy

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: main
          path: source

      - uses: actions/checkout@v2
        with:
          ref: gh-pages
          path: build

      - name: remove all files on the build folder
        working-directory: build
        run: rm -vfr *

      - uses: nicholasphair/sphinx-action@7.0.0
        with:
          docs-folder: "source/docs/"
          # required by #1291
          pre-build-command: |
            apt-get update -y && \
            apt-get install -y git && \
            pip install -y myst-parser && \
            echo "extensions = ['myst_parser']" > conf.py
          build-command: "sphinx-build . ../../build -W"

      - name: disable jekyll
        working-directory: build
        run: touch .nojekyll

      - name: create subdomain CNAME file
        working-directory: build
        run: echo docs.inductiva.ai > CNAME

      - name: copy robots.txt file to root
        working-directory: source/docs
        run: cp robots.txt ../../build/

      - name: Commit and push changes to gh-pages
        working-directory: build
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git add .
          git commit -m "Update GitHub pages from Sphinx build for commit ${GITHUB_SHA}"
          git push origin gh-pages
