name: GH Pages Deploy

on:
  push:
    branches: [main]
    paths-ignore:
      - README.md

jobs:
  build-deploy:
    name: Build and deploy

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: main
          path: source

      - uses: actions/checkout@v2
        with:
          ref: gh-pages
          path: build

      - uses: ammaraskar/sphinx-action@master
        with:
          docs-folder: "source/docs/"
          build-command: "sphinx-build . ../build"

      - name: disable jekyll
        working-directory: build
        run: touch .nojekyll

      - name: Commit and push changes to gh-pages
        working-directory: build
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git add .
          git commit -m "Update GitHub pages from Sphinx build for commit ${GITHUB_SHA}"
          git push origin gh-pages
