name: Trigger web-api version update

on:
  push:
    tags:
      - "*"

jobs:
  trigger-server-update:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger a workflow in the server repository
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.BOT_REPO_ACCESS }}
          repository: inductiva/inductiva-web-api
          event-type: update-version
          client-payload: '{"tag": "${{ github.ref }}" }'
