name: Check add_simulator label
on:
  pull_request:
    types:
      - labeled
jobs:
  add-comment:
    if: github.event.label.name == 'add_simulator'
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
        - name: Comment on PR
          uses: peter-evans/create-or-update-comment@v1
          with:
            issue-number: ${{ github.event.pull_request.number }}
            body: |
              "Test Comment"
            token: ${{ secrets.GITHUB_TOKEN }}

