name: Repository setup

on:
  push:
    branches: [main]

jobs:
  setup:

    if: ${{ github.event.created }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Replace variables
        uses: jacobtomlinson/gha-find-replace@master
        with:
          find: "\\{\\{GITHUB_REPOSITORY\\}\\}"
          replace: ${{ github.repository }}
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Automated repository setup
          commit_options: "--no-verify --signoff"
