name: Run Docs Snippets

on:
  pull_request:
    branches:
      - main  # Only trigger when the target branch is main

jobs:
  run_docs_snippets:
    runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@v3
        - name: Set up Python ${{ matrix.python-version }}
          uses: actions/setup-python@v3
          with:
            python-version: ${{ matrix.python-version }}
        - name: Install dependencies
          env:
            BOT_REPO_ACCESS: ${{ secrets.BOT_REPO_ACCESS }}
          run: |
            sudo apt-get install -y libglu1-mesa ca-certificates
            python -m pip install --upgrade pip setuptools wheel
            python -m pip install pytest pytest-custom_exit_code toml pytest-markdown-docs pytest-xdist
            if [[ -f requirements.txt ]]; then python -m pip install -r requirements.txt; fi
        - name: Test docs with pytest pytest-markdown-docs
          run: |
            if [ "${{ github.ref }}" = "refs/heads/main" ]; then
            export INDUCTIVA_API_KEY=${{ secrets.API_TEST_KEY }}
            else
            export INDUCTIVA_API_KEY=${{ secrets.API_DEV_TEST_KEY }}
            export INDUCTIVA_API_URL=https://api-dev.inductiva.ai
            fi
            pytest -n auto --markdown-docs --confcutdir=docs/ docs/simulators/CaNS.md docs/simulators/FDS.md docs/simulators/SWASH.md