name: Run Docs Snippets

on:
  pull_request:
    branches:
      - main  # Only trigger when the target branch is main

jobs:
  run_docs_snippets:
    runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@v3
        - name: Set up Python ${{ matrix.python-version }}
          uses: actions/setup-python@v3
          with:
            python-version: ${{ matrix.python-version }}
        - name: Install dependencies
          env:
            BOT_REPO_ACCESS: ${{ secrets.BOT_REPO_ACCESS }}
          run: |
            sudo apt-get install -y libglu1-mesa ca-certificates
            python -m pip install --upgrade pip setuptools wheel
            python -m pip install pytest pytest-custom_exit_code toml
            if [[ -f requirements.txt ]]; then python -m pip install -r requirements.txt; fi
        - name: Test code snipets
          run: |
            if [ "${{ github.ref }}" = "refs/heads/main" ]; then
            export INDUCTIVA_API_KEY=${{ secrets.API_TEST_KEY }}
            else
            export INDUCTIVA_API_KEY=${{ secrets.API_DEV_TEST_KEY }}
            export INDUCTIVA_API_URL=https://api-dev.inductiva.ai
            fi
            python inductiva/tests/test_simulators/amr_wind/amr_wind.py
            python inductiva/tests/test_simulators/cans/cans.py
            python inductiva/tests/test_simulators/dualsphysics/dualsphysics.py
            python inductiva/tests/test_simulators/fds/fds.py
            python inductiva/tests/test_simulators/fvcom/fvcom.py
            python inductiva/tests/test_simulators/gromacs/gromacs.py
            python inductiva/tests/test_simulators/nwchem/nwchem.py
            python inductiva/tests/test_simulators/openfast/openfast.py
            python inductiva/tests/test_simulators/openfoam_esi/openfoam_esi.py
            python inductiva/tests/test_simulators/openfoam_foundation/openfoam_foundation.py
            python inductiva/tests/test_simulators/quantum_espresso/quantum_espresso.py
            python inductiva/tests/test_simulators/reef3d/reef3d.py
            python inductiva/tests/test_simulators/schism/schism.py
            python inductiva/tests/test_simulators/splishsplash/splishsplash.py
            python inductiva/tests/test_simulators/swan/swan.py
            python inductiva/tests/test_simulators/swash/swash.py
            python inductiva/tests/test_simulators/xbeach/xbeach.py
