name: Run Tests on Multiple Machines

on:
  push:
    branches: [main]
  pull_request:


jobs:
  run_on_linux_arm64:
    runs-on: Linux_ARM64_2cores

    steps:
        - uses: actions/checkout@v3
        - name: Set up Python ${{ matrix.python-version }}
          uses: actions/setup-python@v3
          with:
            python-version: ${{ matrix.python-version }}
        - name: Install dependencies
          env:
            BOT_REPO_ACCESS: ${{ secrets.BOT_REPO_ACCESS }}
          run: |
            sudo apt-get install -y libglu1-mesa ca-certificates
            python -m pip install --upgrade pip setuptools wheel
            python -m pip install pytest pytest-custom_exit_code toml pytest-markdown-docs
            if [[ -f requirements.txt ]]; then python -m pip install -r requirements.txt; fi
        - name: Test with pytest
          run: |
            if [ "${{ github.ref }}" = "refs/heads/main" ]; then
            export INDUCTIVA_API_KEY=${{ secrets.API_TEST_KEY }}
            else
            export INDUCTIVA_API_KEY=${{ secrets.API_DEV_TEST_KEY }}
            export INDUCTIVA_API_URL=https://api-dev.inductiva.ai
            fi
            pytest --suppress-no-test-exit-code
  run_on_windows_arm64:
    runs-on: Windows_ARM64_4cores

    steps:
        - uses: actions/checkout@v3
        - name: Set up Python ${{ matrix.python-version }}
          uses: actions/setup-python@v3
          with:
            python-version: ${{ matrix.python-version }}
        - name: Verify Python Installation
          shell: powershell
          run: |
            python --version
            where python  # Confirm Python's path
        - name: Install dependencies
          env:
            BOT_REPO_ACCESS: ${{ secrets.BOT_REPO_ACCESS }}
          shell: powershell
          run: |
            $python = "${{ steps.setup-python.outputs.python-path }}"
            & $python -m pip install --upgrade pip setuptools wheel
            & $python -m pip install pytest pytest-custom_exit_code toml pytest-markdown-docs
            if (Test-Path "requirements.txt") { & $python -m pip install -r requirements.txt }
        - name: Test with pytest
          shell: powershell
          run: |
            if ("${{ github.ref }}" -eq "refs/heads/main") {
              $env:INDUCTIVA_API_KEY = "${{ secrets.API_TEST_KEY }}"
            } else {
              $env:INDUCTIVA_API_KEY = "${{ secrets.API_DEV_TEST_KEY }}"
              $env:INDUCTIVA_API_URL = "https://api-dev.inductiva.ai"
            }
            & python -m pytest --suppress-no-test-exit-code
  run_on_windows_x64:
    runs-on: Windows_x64_8cores

    steps:
        - uses: actions/checkout@v3
        - name: Set up Python ${{ matrix.python-version }}
          uses: actions/setup-python@v3
          with:
            python-version: ${{ matrix.python-version }}
        - name: Verify Python Installation
          shell: powershell
          run: |
            Write-Output "Python version:"
            & "${{ steps.setup-python.outputs.python-path }}" --version
        - name: Install dependencies
          env:
            BOT_REPO_ACCESS: ${{ secrets.BOT_REPO_ACCESS }}
          shell: powershell
          run: |
            $python = "${{ steps.setup-python.outputs.python-path }}"
            & $python -m pip install --upgrade pip setuptools wheel
            & $python -m pip install pytest pytest-custom_exit_code toml pytest-markdown-docs
            if (Test-Path "requirements.txt") { & $python -m pip install -r requirements.txt }
        - name: Test with pytest
          shell: powershell
          run: |
            if ("${{ github.ref }}" -eq "refs/heads/main") {
              $env:INDUCTIVA_API_KEY = "${{ secrets.API_TEST_KEY }}"
            } else {
              $env:INDUCTIVA_API_KEY = "${{ secrets.API_DEV_TEST_KEY }}"
              $env:INDUCTIVA_API_URL = "https://api-dev.inductiva.ai"
            }
            & python -m pytest --suppress-no-test-exit-code